# Generated by Django 5.2.12 on 2026-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLCHECK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('Prediction', models.CharField(max_length=20)),
                ('Probability', models.FloatField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
